### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by flydev-fr**
Please read the commits to get what I added then let me know what you think 😊🤙

Note: I will check how to add/run dependencies from the packages.json on pip install command. If you already know how to do it, please tell me.

### CODE REVIEW

**Comment by rajasimon** [comment]
Thank you so much for the contribution. I will check this code and revert back in two business days.

**Comment by rajasimon** [comment]
The fact the it's not high priority. Let assign some solid time slot so that I can finish and merge

**Comment by flydev-fr** [comment]
I made again some modif, I will send another PR 👍

**Comment by rajasimon** [comment]
Can you also remove pipenv file and place just requirements.txt in your next release thnx.

**Comment by flydev-fr** [comment]
Yes, that's one of the changes.

**Pull request merged**
